### ISSUE TITLE
Firebase C++ SDK Build Error on Windows (3.1.1 → 3.2.0)

### ISSUE THREAD

**Issue by omerfarukdinder** [serverpod/serverpod#4583]
### Describe the bug

After upgrading from Serverpod 3.1.1 to 3.2.0, the Flutter Windows build fails with C4996 compiler warnings being treated as errors in the Firebase C++ SDK.

### Actual Behavior
The build process fails with multiple C4996 warnings (unsafe `strncpy` usage) being converted to errors in `firebase/variant.h`.

### Error Message
```powershell
C:\projects\senkrofit\senkrofit_flutter\build\windows\x64\extracted\firebase_cpp_sdk_windows\include\firebase/variant.h(801,7): error C2220: warning treated as error
C:\projects\senkrofit\senkrofit_flutter\build\windows\x64\extracted\firebase_cpp_sdk_windows\include\firebase/variant.h(801,7): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS.
C:\projects\senkrofit\senkrofit_flutter\build\windows\x64\extracted\firebase_cpp_sdk_windows\include\firebase/variant.h(827,7): warning C4996: 'strncpy': This function or variable may be unsafe.

Error: Build process failed.
Exited (1).
```

### Steps to Reproduce
1. Update Serverpod Flutter project from 3.1.1 to 3.2.0
2. Run `flutter run` on Windows platform
3. Build fails during firebase_auth plugin compilation

### Additional Context
- This issue only occurs on Windows platform
- The same project builds successfully on other platforms (Android)
- Version 3.1.1 builds without issues on Windows

### Expected behavior

The Flutter Windows application should build successfully without compiler errors.

### Library version

Flutter 3.38.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8b87286849 (4 days ago) • 2026-01-08 10:49:17 -0800
Engine • hash 6f3039bf7c3cb5306513c75092822d4d94716003 (revision 78fc3012e4) (5 days ago) • 2026-01-07
18:42:12.000Z
Tools • Dart 3.10.7 • DevTools 2.51.1

### Platform information

- **Serverpod Version**: 3.1.1 → 3.2.0
- **Flutter Target**: Windows (x64)
- **Build Mode**: Debug
- **Compiler**: MSVC (Visual Studio)

### Additional context

```cpp
// windows/flutter/generated_plugins.cmake
#
# Generated file, do not edit.
#

list(APPEND FLUTTER_PLUGIN_LIST
  connectivity_plus
  firebase_auth                                            // Added in version 3.2.2
  firebase_core                                            // Added in version 3.2.2
  flutter_secure_storage_windows
)

list(APPEND FLUTTER_FFI_PLUGIN_LIST
)

set(PLUGIN_BUNDLED_LIBRARIES)

foreach(plugin ${FLUTTER_PLUGIN_LIST})
  add_subdirectory(flutter/ephemeral/.plugin_symlinks/${plugin}/windows plugins/${plugin})
  target_link_libraries(${BINARY_NAME} PRIVATE ${plugin}_plugin)
  list(APPEND PLUGIN_BUNDLED_LIBRARIES $<TARGET_FILE:${plugin}_plugin>)
  list(APPEND PLUGIN_BUNDLED_LIBRARIES ${${plugin}_bundled_libraries})
endforeach(plugin)

foreach(ffi_plugin ${FLUTTER_FFI_PLUGIN_LIST})
  add_subdirectory(flutter/ephemeral/.plugin_symlinks/${ffi_plugin}/windows plugins/${ffi_plugin})
  list(APPEND PLUGIN_BUNDLED_LIBRARIES ${${ffi_plugin}_bundled_libraries})
endforeach(ffi_plugin)
```

---

```cpp
// windows/flutter/generated_plugin_registrant.cc
//
//  Generated file. Do not edit.
//

// clang-format off

#include "generated_plugin_registrant.h"

#include <connectivity_plus/connectivity_plus_windows_plugin.h>
#include <firebase_auth/firebase_auth_plugin_c_api.h>                                            // Added in version 3.2.2
#include <firebase_core/firebase_core_plugin_c_api.h>                                            // Added in version 3.2.2
#include <flutter_secure_storage_windows/flutter_secure_storage_windows_plugin.h>

void RegisterPlugins(flutter::PluginRegistry* registry) {
  ConnectivityPlusWindowsPluginRegisterWithRegistrar(
      registry->GetRegistrarForPlugin("ConnectivityPlusWindowsPlugin"));
  FirebaseAuthPluginCApiRegisterWithRegistrar(
      registry->GetRegistrarForPlugin("FirebaseAuthPluginCApi"));                                            // Added in version 3.2.2
  FirebaseCorePluginCApiRegisterWithRegistrar(
      registry->GetRegistrarForPlugin("FirebaseCorePluginCApi"));                                            // Added in version 3.2.2
  FlutterSecureStorageWindowsPluginRegisterWithRegistrar(
      registry->GetRegistrarForPlugin("FlutterSecureStorageWindowsPlugin"));
}

```

### How experienced are you with this library?

Beginner - Just getting started with this library

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by marcelomendoncasoares** [comment]
Thanks for the report, @omerfarukdinder!

This is under fix by moving the Firebase IDP out of the main IDP Flutter package. A similar issue was also reported at #4566 and the fix is already under way with #4577. Version `3.2.1` will be out with this fix by tomorrow.

**Comment by omerfarukdinder** [comment]
That's good to hear. Thank you for your quick response.
